package myFirstPackage

type RouterGroup struct {
    // Code generated by github.com/flipped-aurora/gin-vue-admin/server Begin; DO NOT EDIT.

	StudentInfoRouter
	StudentGirlfriendRouter
	// Code generated by github.com/flipped-aurora/gin-vue-admin/server End; DO NOT EDIT.
}
